apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-gqhr
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-gqhr
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-gqhr
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-gqhr
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-gqhr
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-sjgy-tenant/rhtap-demo-app/hacbs-test-project-gqhr@sha256:db59d01a383117f946a0bced40367b7b9d9a2cf81bc4735405350b64004a7845
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
